### ISSUE TITLE
New restaurant: Välfärden

### ISSUE THREAD

**Issue by arnefischereit** [PerssonP/malmofoods#5]
Hey, great tool, thank you!

We like to also go to [Välfärden](https://valfarden.nu/dagens-lunch/). Would you mind adding that?

**Comment by PerssonP** [comment]
Thank you for the feedback!
I'll look into adding Välfärden once it re-opens after vacation and resumes posting its menu.

**Comment by PerssonP** [comment]
Välfärden has been added and is now up on the public site. Thanks again for the suggestion :)
